"""Regenerate the README and docs screenshots from the running app.

Section 17.3 of the style guide asks that pictures be generated by the app
rather than hand-taken, so they cannot go stale without the build noticing.

Usage, from the repository root:

    pip install playwright && python -m playwright install chromium
    python docs/seed-demo.py          # writes shots.db with demo devices
    python docs/shots.py docs/images  # writes the pictures

The database it reads is a throwaway fixture. It never touches /data.
"""
import os, sys, threading, time, pathlib
root = str(pathlib.Path(__file__).resolve().parent.parent); os.chdir(root); sys.path.insert(0, root)
os.environ['DB_PATH'] = os.path.join(root, 'shots.db')
os.environ['ADMIN_PASSWORD'] = 'smoketest123'
os.environ['POLL_INTERVAL'] = '100000'          # keep the poller off our seeded cache
import uvicorn
from playwright.sync_api import sync_playwright

srv = uvicorn.Server(uvicorn.Config('backend.main:app', host='127.0.0.1', port=8211, log_level='error'))
threading.Thread(target=srv.run, daemon=True).start()
time.sleep(7)

out = pathlib.Path(sys.argv[1]); out.mkdir(parents=True, exist_ok=True)
errors = []

with sync_playwright() as pw:
    b = pw.chromium.launch()
    ctx = b.new_context(viewport={'width': 1500, 'height': 1000}, device_scale_factor=2)
    pg = ctx.new_page()
    pg.on('console', lambda m: errors.append(f'{m.type}: {m.text}') if m.type == 'error' else None)
    pg.on('pageerror', lambda e: errors.append(f'pageerror: {e}'))

    pg.goto('http://127.0.0.1:8211/', wait_until='networkidle')
    pg.screenshot(path=out / '00-login.png')

    pg.fill('#hlm-user', 'admin'); pg.fill('#hlm-pass', 'smoketest123')
    pg.click('button[type=submit]'); pg.wait_for_load_state('networkidle'); time.sleep(2.5)
    pg.screenshot(path=out / '01-dashboard.png')

    def dev(name):
        pg.click(f'.nav-row:has-text("{name}")'); time.sleep(1.6)

    def tab(label):
        pg.click(f'.segmented button:has-text("{label}")'); time.sleep(1.4)

    dev('core-sw-01');  pg.screenshot(path=out / '02-switch-overview.png')
    tab('Ports');       pg.screenshot(path=out / '03-switch-ports.png')
    tab('PoE');         pg.screenshot(path=out / '04-switch-poe.png')
    tab('Connected');   pg.screenshot(path=out / '05-switch-connected.png')

    dev('esxi-01');     pg.screenshot(path=out / '06-server-overview.png')
    tab('Hardware');    pg.screenshot(path=out / '07-server-hardware.png')
    tab('Power');       pg.screenshot(path=out / '08-server-power.png')
    tab('Sensors');     pg.screenshot(path=out / '09-server-sensors.png')

    dev('apc-rack');    pg.screenshot(path=out / '10-ups-overview.png')
    tab('Graphs');      time.sleep(2.5); pg.screenshot(path=out / '11-ups-graphs.png')

    pg.click('.nav-row:has-text("Services")');   time.sleep(1.5)
    pg.screenshot(path=out / '12-services.png')
    pg.click('.nav-row:has-text("Monitoring")'); time.sleep(1.5)
    pg.screenshot(path=out / '13-monitoring.png')

    # The add-device dialog, the biggest form in the app.
    pg.click('.btn-primary:has-text("Add device")'); time.sleep(1.2)
    pg.screenshot(path=out / '14-add-device.png')
    pg.keyboard.press('Escape'); pg.click('.btn-icon[title=Close]'); time.sleep(0.8)

    # §3: "Test both themes on every screen. A theme found only in a screenshot
    # of the dark one is a theme nobody tried." So walk the whole app again in
    # light, into out/light/.
    light = out / "light"
    light.mkdir(exist_ok=True)
    pg.click('.nav-row:has-text("Dashboard")'); time.sleep(1.0)
    pg.click('.segmented button[title=Light]'); time.sleep(1.0)
    pg.screenshot(path=light / '01-dashboard.png')

    dev('core-sw-01');  pg.screenshot(path=light / '02-switch-overview.png')
    tab('Ports');       pg.screenshot(path=light / '03-switch-ports.png')
    tab('PoE');         pg.screenshot(path=light / '04-switch-poe.png')
    tab('Connected');   pg.screenshot(path=light / '05-switch-connected.png')
    tab('VLANs');       pg.screenshot(path=light / '05b-switch-vlans.png')

    dev('esxi-01');     pg.screenshot(path=light / '06-server-overview.png')
    tab('Hardware');    pg.screenshot(path=light / '07-server-hardware.png')
    tab('Storage');     pg.screenshot(path=light / '07b-server-storage.png')
    tab('Network');     pg.screenshot(path=light / '07c-server-network.png')
    tab('Power');       pg.screenshot(path=light / '08-server-power.png')
    tab('Sensors');     pg.screenshot(path=light / '09-server-sensors.png')
    tab('Console');     pg.screenshot(path=light / '09b-server-console.png')

    dev('apc-rack');    pg.screenshot(path=light / '10-ups-overview.png')
    tab('Graphs');      time.sleep(2.0); pg.screenshot(path=light / '11-ups-graphs.png')
    tab('Shutdown');    pg.screenshot(path=light / '11b-ups-shutdown.png')
    tab('Notifications'); pg.screenshot(path=light / '11c-notifications.png')

    pg.click('.nav-row:has-text("Services")');   time.sleep(1.2)
    pg.screenshot(path=light / '12-services.png')
    pg.click('.nav-row:has-text("Monitoring")'); time.sleep(1.2)
    pg.screenshot(path=light / '13-monitoring.png')
    pg.click('.btn-primary:has-text("Add device")'); time.sleep(1.0)
    pg.screenshot(path=light / '14-add-device.png')
    pg.click('.btn-icon[title=Close]'); time.sleep(0.6)

    # And the dark screens the first pass did not reach, so the two sets match.
    pg.click('.segmented button[title=Dark]'); time.sleep(0.8)
    dev('core-sw-01'); tab('VLANs');  pg.screenshot(path=out / '05b-switch-vlans.png')
    dev('esxi-01');    tab('Storage'); pg.screenshot(path=out / '07b-server-storage.png')
    tab('Network');    pg.screenshot(path=out / '07c-server-network.png')
    tab('Console');    pg.screenshot(path=out / '09b-server-console.png')
    dev('apc-rack');   tab('Shutdown'); pg.screenshot(path=out / '11b-ups-shutdown.png')
    tab('Notifications'); pg.screenshot(path=out / '11c-notifications.png')

    b.close()

srv.should_exit = True
print('shots written to', out)
print('CONSOLE ERRORS:', len(errors))
for e in dict.fromkeys(errors): print('   ', e[:220])
